### ISSUE TITLE
If no advanced-woo-search plugin - no criticals

### ISSUE THREAD

**Issue by goodpenguins** [chyvak1831/starter#143]
![image](https://user-images.githubusercontent.com/17085475/152283598-7c7b3c61-b7bc-4226-b21e-9f47e5446121.png)

**Comment by goodpenguins** [comment]
I think this is when there is no Woocommerce on the site at all

**Comment by chyvak1831** [comment]
here existing task for that
https://github.com/chyvak1831/starter/issues/133
